Repository projectsyn/component-lieutenant, pull requests merged in 2022-03, with the labels that each got.

#28 Make component support both kube-libsonnet `v1.14.6' and 'v1.19.0'
  component/api.jsonnet
  tests/golden/defaults/lieutenant/lieutenant/20_api/ingress-lieutenant-api.yaml
  tests/unit/api_test.go
  tests/unit/defaults_test.go
  tests/unit/rbac_test.go
Labels: bug

#30 Add option to configure auth path when connecting to external an vault
  class/defaults.yml
  component/operator.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_tenants.yaml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_tenanttemplates.yaml
  tests/golden/defaults/lieutenant/lieutenant/10_operator/deployment.yaml
  tests/unit/defaults_test.go
Labels: enhancement

#31 Fix typo that rendered the Vault auth path unusable
  component/operator.jsonnet
  tests/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/10_operator/deployment.yaml
  tests/unit/operator_test.go
Labels: bug

#35 Add how-to on deploying Lieutenant in a vcluster
  docs/modules/ROOT/pages/how-tos/vcluster.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#36 Update dependency docker.io/projectsyn/lieutenant-api to v0.9.0
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/20_api/deployment-lieutenant-api.yaml
  tests/unit/defaults_test.go
Labels: dependency

#37 Add option to configure environment variables for API
  class/defaults.yml
  component/api.jsonnet
  docs/modules/ROOT/pages/how-tos/vcluster.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/20_api/deployment-lieutenant-api.yaml
  tests/unit/api_test.go
Labels: enhancement
