Repository projectsyn/component-lieutenant, pull requests merged in 2022-04, with the labels that each got.

#40 Add support for configuring a `TenantTemplate`
  class/defaults.yml
  class/lieutenant.yml
  component/tenanttemplate.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/60_tenant_template.yaml
  tests/unit/defaults_test.go
Labels: enhancement

#23 Update dependency docker.io/projectsyn/steward to v0.7.0
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/20_api/deployment-lieutenant-api.yaml
  tests/unit/defaults_test.go
Labels: dependency

#43 Remove version check tests
  tests/unit/api_test.go
  tests/unit/defaults_test.go
  tests/unit/operator_test.go
Labels: ignore

#42 Update dependency docker.io/projectsyn/lieutenant-api to v0.9.1
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/20_api/deployment-lieutenant-api.yaml
Labels: dependency
