Repository projectsyn/component-lieutenant, pull requests merged in 2024-05, with the labels that each got.

#94 Configure renovate to automerge patch level PRs
  renovate.json
Labels: change

#96 Update quay.io/projectsyn/lieutenant-operator Docker tag to v1.5.1
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/10_operator/deployment.yaml
Labels: dependency

#98 Update quay.io/projectsyn/lieutenant-operator Docker tag to v1.5.2
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/10_operator/deployment.yaml
Labels: automerge

#99 Update quay.io/projectsyn/lieutenant-operator Docker tag to v1.5.3
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_clusters.yaml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_gitrepos.yaml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_tenants.yaml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_tenanttemplates.yaml
  tests/golden/defaults/lieutenant/lieutenant/10_operator/clusterrole.yaml
  tests/golden/defaults/lieutenant/lieutenant/10_operator/deployment.yaml
Labels: automerge

#100 Update quay.io/projectsyn/lieutenant-operator Docker tag to v1.6.0
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_clusters.yaml
  tests/golden/defaults/lieutenant/lieutenant/10_operator/deployment.yaml
Labels: dependency

#95 Update docker.io/projectsyn/steward Docker tag to v0.11.2
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/20_api/deployment-lieutenant-api.yaml
Labels: dependency

#101 Update docker.io/projectsyn/lieutenant-api Docker tag to v0.12.0
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/20_api/deployment-lieutenant-api.yaml
Labels: dependency

#102 Update quay.io/projectsyn/lieutenant-operator Docker tag to v1.6.1
  class/defaults.yml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_clusters.yaml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_gitrepos.yaml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_tenants.yaml
  tests/golden/defaults/lieutenant/lieutenant/00_crds/syn.tools_tenanttemplates.yaml
  tests/golden/defaults/lieutenant/lieutenant/10_operator/deployment.yaml
Labels: dependency, automerge
